---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/boards":
    post:
      summary: Creates a board
      tags:
      - Boards
      parameters: []
      responses:
        '201':
          description: board created
        '404':
          description: Name can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/boards/{id}":
    get:
      summary: Retrieves a board
      tags:
      - Boards
      - Another Tag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: board found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                required:
                - name
        '404':
          description: board not found
        '406':
          description: unsupported accept header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
